nsi_dicts_all = {
    "nsi_stage_1_dict": {
        "nsi_mkb10": {"dict_id": 13, "dict_name": "Справочник Министерства здравоохранения РФ"},
        "nsi_o001": {"dict_id": 31, "dict_name": "Общероссийский классификатор стран мира (OKSM)"},
        "nsi_o002": {"dict_id": 32,
                     "dict_name": "Общероссийский классификатор административно-территориального деления (ОКАТО)"},
        "nsi_o003": {"dict_id": 76,
                     "dict_name": "Общероссийский классификатор видов экономической деятельности (OKVED)"},
        "nsi_o004": {"dict_id": 77, "dict_name": "Общероссийский классификатор форм собственности (OKFS)"},
        "nsi_o005": {"dict_id": 78, "dict_name": "Общероссийский классификатор организационно-правовых форм (OKOPF)"},
        "nsi_f005": {"dict_id": 62, "dict_name": "Классификатор статусов оплаты медицинской помощи (StatOpl)"},
        "nsi_f006": {"dict_id": 5, "dict_name": "Классификатор видов контроля"},
        "nsi_f007": {"dict_id": 6, "dict_name": "Классификатор ведомственной принадлежности медицинской организации"},
        "nsi_f008": {"dict_id": 7,
                     "dict_name": "Классификатор типов документов, подтверждающих факт страхования по ОМС (TipOMS)"},
        "nsi_f009": {"dict_id": 63, "dict_name": "Классификатор статуса застрахованного лица (StatZL)"},
        "nsi_f011": {"dict_id": 9, "dict_name": "Классификатор типов документов, удостоверяющих личность (Tipdoc)"},
        "nsi_f014": {"dict_id": 10, "dict_name": "Классификатор причин отказа в оплате медицинской помощи"},
        "nsi_f015": {"dict_id": 65, "dict_name": "Классификатор федеральных округов (Okrug)"},
        "nsi_f016": {"dict_id": 66, "dict_name": "Классификатор тем обращений граждан (Theme)"},
        "nsi_q017": {"dict_id": 79, "dict_name": "Перечень категорий проверок ФЛК и МЭК (TEST_K)"},
        "nsi_q019": {"dict_id": 33, "dict_name": "Классификатор типов передаваемых данных"},
        "nsi_q020": {"dict_id": 80,
                     "dict_name": "Классификатор типов элементов файлов информационного обмена (TYPE_EL)"},
        "nsi_q021": {"dict_id": 81,
                     "dict_name": "Классификатор форматов элементов файлов информационного обмена (FORM_EL)"},
        "nsi_n001": {"dict_id": 14, "dict_name": "Классификатор противопоказаний и отказов (OnkPrOt)"},
        "nsi_n007": {"dict_id": 19, "dict_name": "Классификатор гистологических признаков (OnkMrf)"},
        "nsi_n010": {"dict_id": 21, "dict_name": "Классификатор маркеров (OnkIgh)"},
        "nsi_n013": {"dict_id": 23, "dict_name": "Классификатор типов лечения (OnkLech)"},
        "nsi_n014": {"dict_id": 24, "dict_name": "Классификатор типов хирургического лечения (OnkHir)"},
        "nsi_n015": {"dict_id": 25, "dict_name": "Классификатор линий лекарственной терапии (OnkLek_L)"},
        "nsi_n016": {"dict_id": 26, "dict_name": "Классификатор циклов лекарственной терапии (OnkLek_V)"},
        "nsi_n017": {"dict_id": 27, "dict_name": "Классификатор типов лучевой терапии (OnkLuch)"},
        "nsi_n018": {"dict_id": 28, "dict_name": "Классификатор поводов обращения (OnkReas)"},
        "nsi_n019": {"dict_id": 29, "dict_name": "Классификатор целей консилиума (OnkCons)"},
        "nsi_n020": {"dict_id": 30,
                     "dict_name": "Классификатор лекарственных препаратов, применяемых при проведении лекарственной терапии (OnkLekp)"},
        "nsi_r001": {"dict_id": 82, "dict_name": "Классификатор причин внесения изменений в РС ЕРЗ (PRICIN)"},
        "nsi_r002": {"dict_id": 83, "dict_name": "Классификатор форм изготовления полиса (FORM)"},
        "nsi_r003": {"dict_id": 84, "dict_name": "Классификатор способов подачи заявления (SPOS)"},
        "nsi_r004": {"dict_id": 85,
                     "dict_name": "Классификатор результатов обработки заявки на внесение изменений в РС ЕРЗ (REZ)"},
        "nsi_r005": {"dict_id": 86, "dict_name": "Классификатор причин исключения из реестра СМО (ISKSMO)"},
        "nsi_r006": {"dict_id": 87, "dict_name": "Классификатор причин исключения из реестра МО (ISKMO)"},
        "nsi_r007": {"dict_id": 88, "dict_name": "Классификатор признака подчиненности СМО (GLSMO)"},
        "nsi_r008": {"dict_id": 34, "dict_name": "Классификатор признака подчиненности МО"},
        "nsi_r009": {"dict_id": 89,
                     "dict_name": "Классификатор организаций, представляющих кандидатуру эксперта качества медицинской помощи (ORPREX)"},
        "nsi_r010": {"dict_id": 90,
                     "dict_name": "Классификатор причин исключения эксперта качества медицинской помощи из территориального реестра (ISKEX)"},
        "nsi_r011": {"dict_id": 91, "dict_name": "Классификатор квалификационных категорий (KVKAT)"},
        "nsi_r012": {"dict_id": 92, "dict_name": "Классификатор ученых степеней (UCHST)"},
        "nsi_r013": {"dict_id": 93, "dict_name": "Классификатор главных внештатных специалистов (MZSPEC)"},
        "nsi_r014": {"dict_id": 94, "dict_name": "Классификатор форм изготовления временного свидетельства (FORM_V)"},
        "nsi_v001": {"dict_id": 35,
                     "dict_name": "Номенклатура медицинских услуг. Справочник Министерства здравоохранения РФ (1.2.643.5.1.13.13.11.1070)"},
        "nsi_v002": {"dict_id": 36, "dict_name": "Классификатор профилей оказанной МП"},
        "nsi_v005": {"dict_id": 37, "dict_name": "Классификатор пола застрахованного (Pol)"},
        "nsi_v006": {"dict_id": 38, "dict_name": "Классификатор условий оказания медицинской помощи"},
        "nsi_v008": {"dict_id": 39, "dict_name": "Классификатор видов медицинской помощи"},
        "nsi_v010": {"dict_id": 41, "dict_name": "Классификатор способов оплаты медицинской помощи"},
        "nsi_v014": {"dict_id": 43, "dict_name": "Классификатор форм оказания медицинской помощи"},
        "nsi_v016": {"dict_id": 44, "dict_name": "Классификатор результатов диспансеризации"},
        "nsi_v017": {"dict_id": 46, "dict_name": "Классификатор результатов диспансеризации"},
        "nsi_v018": {"dict_id": 47, "dict_name": "Классификатор видов ВМП"},
        "nsi_v020": {"dict_id": 49, "dict_name": "Классификатор профиля койки"},
        "nsi_v021": {"dict_id": 50, "dict_name": "Классификатор медицинских специальностей"},
        "nsi_v022": {"dict_id": 51, "dict_name": "Классификатор моделей пациента при оказании ВМП"},
        "nsi_v024": {"dict_id": 53, "dict_name": "Классификатор классификационных критериев"},
        "nsi_v025": {"dict_id": 54, "dict_name": "Классификатор целей посещения"},
        "nsi_v027": {"dict_id": 55, "dict_name": "Классификатор характера заболевания"},
        "nsi_v028": {"dict_id": 56, "dict_name": "Классификатор видов направления (NAPR_V)"},
        "nsi_v029": {"dict_id": 57, "dict_name": "Классификатор методов диагностического исследования (MET_ISSL)"},
        "nsi_v015": {"dict_id": 96, "dict_name": "Классификатор медицинских специальностей (Medspec)"},
        "nsi_v003": {"dict_id": 95,
                     "dict_name": "Классификатор работ (услуг) при лицензировании медицинской помощи (LicUsl)"},
        "nsi_dn": {"dict_id": 59, "dict_name": "Cведения о диспансерном наблюдении (для SL/P_CEL = 1.3)"},
        "nsi_fmo_povod": {"dict_id": 67, "dict_name": "Справочник медицинских показаний для направления в ФМО"},
        "nsi_newborn_rel_type": {"dict_id": 75, "dict_name": "Тип связи Новорожденный - ЗЛ. Формируется на уровня ХД."},
        "nsi_ill_reason": {"dict_id": 70,
                           "dict_name": "Признаки причинения вреда здоровью в результате совершения противоправных действий."},
        "nsi_address_type": {"dict_id": 58, "dict_name": "Тип адреса. Таблица заполняется на уровне ХД."},
        "nsi_method_inj": {"dict_id": 12, "dict_name": "Пути введения лекарственных препаратов"},
        "nsi_ed_izm": {"dict_id": 1,
                       "dict_name": "Единицы измерения (справочник Мин. Здрава 1.2.643.5.1.13.13.11.1358)"},
        "nsi_med_dev_type": {"dict_id": 11,
                             "dict_name": "Виды медицинских изделий, имплантируемых в организм человека"},
        "nsi_method_vmp": {"dict_id": 143,
                           "dict_name": "Методы лечения пациента при оказании высокотехнологичной медицинской помощи"},
        "nsi_pac_model_vmp": {"dict_id": 148,
                              "dict_name": "Модели пациента при оказании высокотехнологичной медицинской помощи"},
        "nsi_name_vid_vmp": {"dict_id": 144, "dict_name": "Наименования видов высокотехнологичной медицинской помощи"},
        "nsi_profile_mp": {"dict_id": 149, "dict_name": "Профили медицинской помощи"},
        "nsi_treatment_vmp": {"dict_id": 150,
                              "dict_name": "Виды лечения пациента при оказании высокотехнологичной медицинской помощи"},
        "nsi_okfs": {"dict_id": 145, "dict_name": "ОКФС - Общероссийский классификатор форм собственности"},
        "nsi_oktmo": {"dict_id": 147,
                      "dict_name": "ОКТМО Общероссийский классификатор территорий муниципальных образований"},
        "nsi_okopf": {"dict_id": 146, "dict_name": "ОКОПФ Общероссийский классификатор организационно-правовых форм"},
        "nsi_v030": {"dict_id": 153, "dict_name": "Схемы лечения заболевания COVID-19 (TreatReg)"},
        "nsi_v031": {"dict_id": 154, "dict_name": "Группы препаратов для лечения заболевания COVID-19 (GroupDrugs)"},
        "nsi_med_usl": {"dict_id": 152, "dict_name": "Номенклатура медицинских услуг"},
    },
    "nsi_stage_2_dict": {
        "nsi_f010": {"dict_id": 8, "dict_name": "Классификатор субъектов Российской Федерации"},
        "nsi_n002": {"dict_id": 15, "dict_name": "Классификатор стадий (OnkStad)"},
        "nsi_n003": {"dict_id": 16, "dict_name": "Классификатор Tumor (OnkT)"},
        "nsi_n004": {"dict_id": 17, "dict_name": "Классификатор Nodus (OnkN)"},
        "nsi_n005": {"dict_id": 18, "dict_name": "Классификатор Metastasis (OnkM)"},
        "nsi_n008": {"dict_id": 20, "dict_name": "Классификатор результатов гистологических исследований (OnkMrfRt)"},
        "nsi_n009": {"dict_id": 72,
                     "dict_name": "Классификатор соответствия гистологических признаков диагнозам (OnkMrtDS)"},
        "nsi_n011": {"dict_id": 22, "dict_name": "Классификатор значений маркеров (OnkIghRt)"},
        "nsi_n012": {"dict_id": 73, "dict_name": "Классификатор соответствия маркеров диагнозам (OnkIghDS)"},
        "nsi_n021": {"dict_id": 74,
                     "dict_name": "Классификатор соответствия лекарственного препарата схеме лекарственной терапии (OnkLpsh)"},
        "nsi_v009": {"dict_id": 40, "dict_name": "Классификатор результатов обращения за медицинской помощью"},
        "nsi_v012": {"dict_id": 42, "dict_name": "Классификатор исходов заболевания"},
        "nsi_v019": {"dict_id": 48, "dict_name": "Классификатор методов ВМП"},
        "nsi_v023": {"dict_id": 52, "dict_name": "Классификатор клинико-статистических групп (KSG)"},
        "nsi_v026": {"dict_id": 98, "dict_name": "Классификатор клинико-профильных групп (KPG)"},
        "nsi_v016_dtrule": {"dict_id": 45,
                            "dict_name": "Допустимые для типа диспансеризации значения результата диспансеризации"},
        "nsi_f030": {"dict_id": 141, "dict_name": "Единый реестр медицинских организаций (МО)"},
        "nsi_v019_diag": {"dict_id": 97, "dict_name": "Верхние уровни кодов диагноза по МКБ для метода ВМП"},
        "nsi_vid_vmp": {"dict_id": 151, "dict_name": "Виды высокотехнологичной медицинской помощи"},
        "nsi_v032": {"dict_id": 155, "dict_name": "Сочетание схемы лечения и группы препаратов (CombTreat)"},
    },
    "nsi_stage_3_dict": {
        "nsi_f001": {"dict_id": 2, "dict_name": "Справочник территориальных фондов ОМС"},
        "nsi_n006": {"dict_id": 71, "dict_name": "Справочник соответствия стадий TNM (OnkTNM)"},
        "nsi_v036": {"dict_id": 157,
                     "dict_name": "Перечень услуг, требующих имплантацию медицинских изделий (ServImplDv)"},
        "nsi_v037": {"dict_id": 158,
                     "dict_name": "Перечень методов ВМП, требующих имплантацию медицинских изделий (MethImplDv)"},
    },
    "nsi_stage_4_dict": {
        "nsi_f002": {"dict_id": 3, "dict_name": "Единый реестр страховых медицинских организаций (СМО)"},
        "nsi_f003": {"dict_id": 4, "dict_name": "Единый реестр медицинских организаций (МО)"},
        "nsi_v033": {"dict_id": 156, "dict_name": "Соответствие кода препарата схеме лечения (DgTreatReg)"},
        "nsi_f001_mtr": {"dict_id": 61, "dict_name": "Реквизиты ТФОМС при осуществлении МТР"},
        "nsi_f001_info": {"dict_id": 60, "dict_name": "Информация о территориальных фондах ОМС"},
        "nsi_f030_podr": {"dict_id": 142,
                          "dict_name": "Единый реестр медицинских организаций (МО) - F030 Новая редакция F003 - Подразделения"},
        "nsi_f042": {"dict_id": 159,
                     "dict_name": "Справочник F042 -  Реестр экспертов качества медицинской помощи, оказанной медицинскими организациями, осуществляющих деятельность в сфере обязательного медицинского страхования по территориальным программам обязательного медицинского страхования (TREKMP)"},
    },
    "nsi_stage_5_dict": {
        "nsi_f013": {"dict_id": 64, "dict_name": "Реестр пунктов выдачи полисов (Punkt)"},
    },
}

scheta_tables = {
    "zl_list_schet_nd": {"tbl_id": 133, "tbl_name": "Таблица для удаления дублей счетов"},
    "doc_ods_id_for_ins": {"tbl_id": 133,
                           "tbl_name": "Таблица для insert dq (временная) - нужна для отбора нужных счетов"},
    "head_zl_list": {"tbl_id": 133, "tbl_name": "Таблица связей(временная) - нужна для отбора нужного пероида"},
    "master_person_identification": {"tbl_id": 107,
                                     "tbl_name": "Пациент - Мастер запись. Атрибуты (ФИО, Даты роздения и т.д.) содержат актуальное значения."},
    "src01_zl_list": {"tbl_id": 133, "tbl_name": "Корневой элемент файла XML - Сведения о медпомощи"},
    "schet": {"tbl_id": 125, "tbl_name": "Счет"},
    "zap_patient_stg": {"tbl_id": 118, "tbl_name": "Временная таблица для таблицы person"},
    "person": {"tbl_id": 118, "tbl_name": "Застрахованное лицо (Пациент)"},
    "src01_zap": {"tbl_id": 132, "tbl_name": "Записи о законченных случаях оказания медицинской помощи"},
    "ins_policy": {"tbl_id": 102, "tbl_name": "Полис застрахованного лица"},
    "patient_src_ids": {"tbl_id": 117, "tbl_name": "Сведения о полисе / пациенте - ссылки на первоисточники"},
    "z_sl_stg": {"tbl_id": 137, "tbl_name": "временная таблица для z_sl"},
    "z_sl": {"tbl_id": 137, "tbl_name": "Сведения о законченном случае"},
    "z_sl_os_sluch": {"tbl_id": 138, "tbl_name": "Признак Особый случай"},
    "z_sl_vnov_m": {"tbl_id": 140, "tbl_name": "Вес при рождении"},
    "sl": {"tbl_id": 127, "tbl_name": "Сведения о случае"},
    "ksg_kpg": {"tbl_id": 103, "tbl_name": "Сведения о КСГ/КПГ"},
    "ksg_kpg_crit": {"tbl_id": 104, "tbl_name": "Классификационный критерий для КСГ/КПГ (KSG_KPG)"},
    "sl_koef": {"tbl_id": 130, "tbl_name": "Коэффициенты сложности лечения пациента"},
    "onk_sl": {"tbl_id": 115, "tbl_name": "Сведения о случае лечения онкологического заболевания"},
    "cons": {"tbl_id": 101, "tbl_name": "Сведения о проведении консилиума"},
    "napr": {"tbl_id": 109, "tbl_name": "Сведения об оформлении направления"},
    "sl_code_mes1": {"tbl_id": 128, "tbl_name": "Код МЭС"},
    "sl_ds": {"tbl_id": 129,
              "tbl_name": "Диагнозы заболевания для случая (соответствует элементам DS0, DS1, DS2, DS3)"},
    "onk_usl": {"tbl_id": 116, "tbl_name": "Сведения об услуге при лечении онкологического заболевания"},
    "usl": {"tbl_id": 136, "tbl_name": "Сведения об услуге"},
    "mr_usl_n": {"tbl_id": 713, "tbl_name": "Сведения о медицинских работниках, выполнивших услугу"},
    "lek_pr": {"tbl_id": 106,
               "tbl_name": "Сведения о введенном лекарственном препарате; Сведения о введенном противоопухолевом лекарственном препарате"},
    "lek_dose": {"tbl_id": 105, "tbl_name": "Сведения о дозе введения лекарственного препарата"},
    "b_diag": {"tbl_id": 99,
               "tbl_name": "Сведения о случае лечения онкологического заболевания - Диагностический блок"},
    "b_prot": {"tbl_id": 100, "tbl_name": "Сведения об имеющихся противопоказаниях и отказах"},
    "med_dev": {"tbl_id": 108, "tbl_name": "Сведения о медицинских изделиях, имплантируемых в организм человека"},
    "schet_src_ids": {"tbl_id": 126, "tbl_name": "Счёт - ссылки на первоисточники"},
    "z_sl_src_ids": {"tbl_id": 139, "tbl_name": "Сведения о законченном случае - ссылки на первоисточники"},
    "sl_src_ids": {"tbl_id": 131, "tbl_name": "Сведения о случае - ссылки на первоисточники"},
}

nsi_dicts_test = {
    "nsi_stage_1_dict": {
        "nsi_n016": {"dict_id": 26, "dict_name": "Классификатор типов лучевой терапии (OnkLuch)"},
    },
    "nsi_stage_2_dict": {
        "nsi_n017": {"dict_id": 27, "dict_name": "Классификатор типов лучевой терапии (OnkLuch)"},
    },
    "nsi_stage_3_dict": {
        "nsi_n018": {"dict_id": 28, "dict_name": "Классификатор типов лучевой терапии (OnkLuch)"},
    },
    "nsi_stage_4_dict": {
        "nsi_n019": {"dict_id": 29, "dict_name": "Классификатор типов лучевой терапии (OnkLuch)"},
    },
    "nsi_stage_5_dict": {
        "nsi_n020": {"dict_id": 30, "dict_name": "Классификатор типов лучевой терапии (OnkLuch)"},
    },
}

ods_tables = {
    "ksg_crit": {"table_id": 177},
    "ksg_koef": {"table_id": 178},
    "lek_dose": {"table_id": 179},
    "meta_nsi": {"table_id": 180},
    "onk_b_diag": {"table_id": 181},
    "onk_b_prot": {"table_id": 182},
    "onk_usl": {"table_id": 183},
    "onk_usl_lek": {"table_id": 184},
    "onk_usl_lek_inj": {"table_id": 185},
    "pers_data": {"table_id": 186},
    "pers_list": {"table_id": 187},
    "pers_load": {"table_id": 188},
    "sank_code_exp": {"table_id": 189},
    "sank_sl_id": {"table_id": 190},
    "sl_code_mes1": {"table_id": 191},
    "sl_cons": {"table_id": 192},
    "sl_ds2": {"table_id": 193},
    "sl_ds2_n": {"table_id": 194},
    "sl_ds3": {"table_id": 195},
    "sl_ds3_n": {"table_id": 194},
    "sl_ksg": {"table_id": 196},
    "sl_lek": {"table_id": 197},
    "sl_napr": {"table_id": 198},
    "sl_naz": {"table_id": 199},
    "sl_onk": {"table_id": 200},
    "sl_usl": {"table_id": 201},
    "usl_med": {"table_id": 202},
    "usl_mr": {"table_id": 203},
    "z_sl_os_sluch": {"table_id": 204},
    "z_sl_sank": {"table_id": 205},
    "z_sl_sl": {"table_id": 206},
    "z_sl_vnov_m": {"table_id": 207},
    "zap": {"table_id": 208},
    "zap_patient": {"table_id": 209},
    "zap_patient_enc": {"table_id": 210},
    "zap_patient_uuid_map": {"table_id": 211},
    "zap_z_sl": {"table_id": 212},
    "zl_list": {"table_id": 213},
}

dds_dq_tables = {
    99: {'table_name': 'b_diag'},
    100: {'table_name': 'b_prot'},
    101: {'table_name': 'cons'},
    102: {'table_name': 'ins_policy'},
    103: {'table_name': 'ksg_kpg'},
    104: {'table_name': 'ksg_kpg_crit'},
    105: {'table_name': 'lek_dose'},
    106: {'table_name': 'lek_pr'},
    107: {'table_name': 'master_person'},
    108: {'table_name': 'med_dev'},
    109: {'table_name': 'napr'},
    110: {'table_name': 'naz'},
    111: {'table_name': 'newborn_person'},
    112: {'table_name': 'newborn_person_rel'},
    113: {'table_name': 'npr'},
    114: {'table_name': 'npr_ds'},
    115: {'table_name': 'onk_sl'},
    116: {'table_name': 'onk_usl'},
    117: {'table_name': 'patient_src_ids'},
    118: {'table_name': 'person'},
    119: {'table_name': 'person_address'},
    120: {'table_name': 'person_ident_doc'},
    121: {'table_name': 'person_inv'},
    122: {'table_name': 'person_mse'},
    123: {'table_name': 'person_tel'},
    124: {'table_name': 'sank'},
    125: {'table_name': 'schet'},
    126: {'table_name': 'schet_src_ids'},
    127: {'table_name': 'sl'},
    128: {'table_name': 'sl_code_mes1'},
    129: {'table_name': 'sl_ds'},
    130: {'table_name': 'sl_koef'},
    131: {'table_name': 'sl_src_ids'},
    132: {'table_name': 'src01_zap'},
    133: {'table_name': 'src01_zl_list'},
    134: {'table_name': 'temp_zap_patient_2021_10'},
    135: {'table_name': 'unident_person'},
    136: {'table_name': 'usl'},
    137: {'table_name': 'z_sl'},
    138: {'table_name': 'z_sl_os_sluch'},
    139: {'table_name': 'z_sl_src_ids'},
    140: {'table_name': 'z_sl_vnov_m'},
    143: {'table_name': 'nsi_method_vmp'},
    214: {'table_name': 'risk_vzaim_lek'},
    215: {'table_name': 'erzl_insured'},
    216: {'table_name': 'erzl_attached'},
    712: {'table_name': 'sank_exp'},
    713: {'table_name': 'mr_usl_n'},
    767: {'table_name': 'sank_src_ids'},
    768: {'table_name': 'src01_exp_zap'},
}
